export interface WorkoutOption {
  id: number;
  workout: string;
}

export const workoutOptions: WorkoutOption[] = [
  { id: 1, workout: "Push-ups" },
  { id: 2, workout: "Pull-ups" },
  { id: 3, workout: "Chin-ups" },
  { id: 4, workout: "Bench Press" },
  { id: 5, workout: "Incline Bench Press" },
  { id: 6, workout: "Overhead Shoulder Press" },
  { id: 7, workout: "Lateral Raises" },
  { id: 8, workout: "Front Raises" },
  { id: 9, workout: "Bicep Curls" },
  { id: 10, workout: "Hammer Curls" },
  { id: 11, workout: "Tricep Dips" },
  { id: 12, workout: "Tricep Pushdowns" },
  { id: 13, workout: "Squats" },
  { id: 14, workout: "Front Squats" },
  { id: 15, workout: "Lunges" },
  { id: 16, workout: "Bulgarian Split Squats" },
  { id: 17, workout: "Step-ups" },
  { id: 18, workout: "Leg Press" },
  { id: 19, workout: "Deadlifts" },
  { id: 20, workout: "Romanian Deadlifts" },
  { id: 21, workout: "Sumo Deadlifts" },
  { id: 22, workout: "Glute Bridges" },
  { id: 23, workout: "Hip Thrusts" },
  { id: 24, workout: "Calf Raises" },
  { id: 25, workout: "Seated Calf Raises" },
  { id: 26, workout: "Plank" },
  { id: 27, workout: "Side Plank" },
  { id: 28, workout: "Russian Twists" },
  { id: 29, workout: "Mountain Climbers" },
  { id: 30, workout: "Bicycle Crunches" },
  { id: 31, workout: "Leg Raises" },
  { id: 32, workout: "Hanging Knee Raises" },
  { id: 33, workout: "Flutter Kicks" },
  { id: 34, workout: "Bird Dogs" },
  { id: 35, workout: "Supermans" },
  { id: 36, workout: "Burpees" },
  { id: 37, workout: "Jumping Jacks" },
  { id: 38, workout: "High Knees" },
  { id: 39, workout: "Butt Kicks" },
  { id: 40, workout: "Skipping Rope" },
  { id: 41, workout: "Running (Treadmill/Outdoor)" },
  { id: 42, workout: "Cycling" },
  { id: 43, workout: "Rowing Machine" },
  { id: 44, workout: "Swimming" },
  { id: 45, workout: "Elliptical Trainer" },
  { id: 46, workout: "Stair Climbing" },
  { id: 47, workout: "Box Jumps" },
  { id: 48, workout: "Jump Squats" },
  { id: 49, workout: "Kettlebell Swings" },
  { id: 50, workout: "Turkish Get-up" },
  { id: 51, workout: "Farmer’s Carry" },
  { id: 52, workout: "Sled Push" },
  { id: 53, workout: "Battle Ropes" },
  { id: 54, workout: "Medicine Ball Slams" },
  { id: 55, workout: "Stretching (Static)" },
  { id: 56, workout: "Dynamic Stretching" },
  { id: 57, workout: "Yoga" },
  { id: 58, workout: "Pilates" },
  { id: 59, workout: "Foam Rolling" },
  { id: 60, workout: "Mobility Drills" }
];

